### ISSUE TITLE
Overview of File Ownership and Modes (Legacy Compatibility)

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/pacifica-archiveinterface#16]
### Pacifica Archive Interface version
master
### Pacifica Core Software versions
master
### Platform Details
Any
### Scenario:
Seems the legacy software had a feature we don't have in the current archive interface. The files on the HSM were mode `0444` after the first write of the file. This prevented second writes from happening after the first was completed and successful. We should consider this and come up with how to handle testing and validating a new feature like this.
### Steps to Reproduce:
1. `chmod 0444` the files on the archive after loading them in.
1. try to stage the file after it's been pushed to tape.
### Expected Result:
Should have staged the file returning 200 OK
### Actual Result:
Got a 500 internal server error, seems the stage method for HPSS is trying to open the file in R/W mode and since the mode of the file is `0444` it's not allowed to do that and errors.

**Comment by dmlb2000** [comment]
@ChristopherKnight do you know what the current state of the file modes are on the three backend types?

**Comment by ChristopherKnight** [comment]
Archive now sets the files to 0444 after a successful write

**Comment by dmlb2000** [comment]
This was fixed with #26
