### ISSUE TITLE
Use tempfile module to determine temporary files directory in cross-platform way

### ISSUE THREAD

**Issue by markborkum** [pacifica/pacifica-archiveinterface#38]
### Pacifica Archive version
1.0

### Pacifica Core Software versions
n/a

### Platform Details
All supported platforms.

### Scenario:
Trying to run the test suite on non-Unix platform.

Codebase should use `tempfile.gettempdir()` function to determine the location of the temporary files directory in a cross-platform way (c.f., https://docs.python.org/2/library/tempfile.html). 

An example affected source file is `archiveinterface/wsgi.py`, where the `PREFIX` variable is [hard-coded](https://github.com/pacifica/pacifica-archiveinterface/blob/be0e20d79c584856a52f760fc8635fb5ecfb63fc/archiveinterface/wsgi.py#L20) to `/tmp`.

### Steps to Reproduce:
n/a

### Expected Result:
n/a

### Actual Result:
n/a

**Comment by dmlb2000** [comment]
I'm going to close this for now, the `pacifica.archiveinterface.wsgi` module is not tested on windows platforms currently. The reference to `/tmp` is also just a default for an environment variable, on windows platforms users are expected to overwrite this for their systems.
