### ISSUE TITLE
Three different ENV Vars for CherryPy Config

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-archiveinterface#65]
### Pacifica Archive Interface version
3c95496bfc723a0625c342728d382efc12e08fd1

### Expected Result:
Seems to be multiple possible ENV Variables you can define for CherryPy config location. Can we use what seems to be becoming the "standard" two variables including:
 * CHERRYPY_CONFIG
 * ARCHIVEINTERFACE_CPCONFIG

The other one, `CP_CONFIG` seems redundant and something easy to forget since we have already standardized on the other two everywhere else.

See reference here: https://github.com/pacifica/pacifica-archiveinterface/blob/3c95496bfc723a0625c342728d382efc12e08fd1/pacifica/archiveinterface/__main__.py#L42

**Comment by dmlb2000** [comment]
The environment variables are all centralized to the `pacifica.archiveinterface.globals` module. The metavar for argparse is simply the string printed when `pacifica-archiveinterface --help` is run.
