### ISSUE TITLE
[Feature Request] Add basic 200 response if service working/functional

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-archiveinterface#86]
### Pacifica Archive Interface version
any

### Pacifica Core Software versions
any

### Platform Details
any

### Scenario:
Trying to get an easy basic response from api to indicate locally, for monitoring purposes, whether or not the api is passing basic functionality tests.

### Expected Result:
```
curl 127.0.0.1:8080/
HTTP/1.1 200
```

**Comment by dmlb2000** [comment]
Yeah, this package is the only package in the platform to do this already ;)

The code...

https://github.com/pacifica/pacifica-archiveinterface/blob/17acf23598c9d77f0d15d994c96bd3739f051b02/pacifica/archiveinterface/rest_generator.py#L49

The test...

https://github.com/pacifica/pacifica-archiveinterface/blob/17acf23598c9d77f0d15d994c96bd3739f051b02/tests/interface_test.py#L130

**Comment by GitBytes** [comment]
:)
Sorry, I got a tad carried away. Had a lot of repos to hit.. Cheers!
